trailingComma = "es5"
tabWidth = 2
singleQuote = true
plugins = ["prettier-plugin-organize-imports", "prettier-plugin-css-order"]

# Don't automatically remove unused imports
organizeImportsSkipDestructiveCodeActions = true
